version: 2.1
orbs:
  cypress: cypress-io/cypress@3.2.1
  node: circleci/node@5.0.2
workflows:
  test:
    jobs:
      - cypress/run:
          install-browsers: true
          start-command: 'npm run test'
          cypress-command: 'npx cypress run'