version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
  node: circleci/node@5.0.2
workflows:
  test:
    jobs:
      - cypress/run:
          install-browsers: true
          start-command: 'npm run start'
          cypress-command: 'npx cypress run --browser chrome'